name: cod_soft_alarm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  alarm: ^3.0.8
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  intl: ^0.19.0
  permission_handler: ^11.2.1
  simple_ripple_animation: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/alarm.png"

flutter:
  uses-material-design: true
